language: bash

script:
  - curl -o miniconda.sh https://repo.anaconda.com/miniconda/Miniconda2-latest-Linux-x86_64.sh
  - bash miniconda.sh -f -b -p "${HOME}/miniconda" && rm -f miniconda.sh
  - export PATH="${HOME}/miniconda/bin:$PATH"
  - conda install -y constructor
  - constructor .
  - rm -rf "${HOME}/miniconda"
  - bash $(ls autoconda*) -f -b -p "${HOME}/miniconda"
  - ansible --version

